# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 02:51
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160117_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='extra',
            field=jsonfield.fields.JSONField(default=dict, max_length=1024),
        ),
    ]
