# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160117_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
