# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_build_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='build',
            unique_together=set([('package', 'build_number', 'version')]),
        ),
    ]
